### ISSUE TITLE
Blake3 replacement

### ISSUE THREAD

**Issue by deven96** [deven96/ahnlich#120]
Blake3 keeps causing issues for crosscompilation. This led to using osxcross and zigbuild
We mostly use it simply just for keeping track of a store key without storing the entirety of the store key. We can replace with an equally fast hasher like [xxhash](https://crates.io/crates/xxhash-rust)

**Comment by Iamdavidonuh** [comment]
Zig is able to compile blake3 cc dependencies, so no need to swap out
