### ISSUE TITLE
AI proxy setup 

### ISSUE THREAD

**Issue by deven96** [deven96/ahnlich#42]
Setting up the ai proxy with the things specified in [ai.md](https://github.com/deven96/ahnlich/blob/main/docs/ai.md)

**Comment by Iamdavidonuh** [comment]
A todo list of what needs to be done.

- [ ] Create Provision for ai types and reflect these types in our spec documents
- [ ] Flesh out queries and server responses for AI proxy
- [ ] Provide interface to connect to the selected AI model on store creation
- [ ] Create an Entry point to run AI Binary. It should run in nonblocking mode, and respond to it's queries
- [ ] Persistence

**Comment by Iamdavidonuh** [comment]
@deven96 I believe the requirements for
Completion has been satisfied.
